language: node_js
node_js:
  - 10
  - 12
  - 13
  - 14
cache: yarn

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      node_js: lts/*
      name: "Codestyle"
      script:
        - yarn lint
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn release
