language: node_js
node_js:
  - 10
  - 12
  - 13
  - 14
cache: yarn

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      node_js: lts/*
      name: "Codestyle"
      script:
        - yarn lint
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - git checkout master
          - git remote set-url origin https://$GH_TOKEN@github.com/${TRAVIS_REPO_SLUG}.git
          - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          - yarn release --yes
