language: node_js
node_js:
  - 10
  - 12
  - 13
  - 14
cache: yarn

stages:
  - test
  - name: release
    if: branch = master

jobs:
  include:
    - stage: test
      node_js: lts/*
      name: "Codestyle"
      script:
        - yarn lint
    - stage: release
      node_js: lts/*
      script:
        - git config --global user.email "31671894+researchgate-bot@users.noreply.github.com"
        - git config --global user.name "ResearchGate Bot"
        - git checkout master
        - git reset --hard origin/master
        - git remote set-url origin https://$GH_TOKEN@github.com/${TRAVIS_REPO_SLUG}.git
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - yarn release --yes
