language: node_js
node_js:
  - 8
  - 10
  - 12
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    - stage: prerelease
      node_js: 10
      if: (NOT type IN (pull_request)) AND (branch = master)
      script:
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
        - yarn pre-release
