language: node_js
node_js:
  - 8
  - 10
cache: yarn
jobs:
  include:
    - stage: test
      script:
        - yarn lint
        - yarn test
    # Uncomment once all tokens are setup
    # - stage: release
    #   node_js: 10
    #   if: branch = master
    #   script:
    #     - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    #     - yarn release
